In [268]:
#Abstract
#The objective of this data is to understand customer demographics and buying behavior. Later during the week, we will use predictive analytics to analyze the most profitable customers and how they interact. After that, we will take targeted actions to increase profitable customer response, retention, and growth.
#For this lab, we will gather the data from 3 csv files that are provided in the files_for_lab folder. Use that data and complete the data cleaning tasks as mentioned later in the instructions.

In [269]:
# 1) Read the three files into python as dataframes

!ls

about.md
file1.csv
file1.xlsx
file2.csv
file2.xlsx
file3.csv
file3.xlsx
files_for_lab
lab-customer-analysis-round-1 W1_D2.ipynb
readme.md


In [270]:
import pandas as pd 
import numpy as np

In [271]:
file1 = pd.read_csv('file1.csv')
file2 = pd.read_csv('file2.csv')
file3 = pd.read_csv('file3.csv')

In [272]:
file1

Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master   
1     QZ44356     Arizona      F              Bachelor   
2     AI49188      Nevada      F              Bachelor   
3     WW63253  California      M              Bachelor   
4     GA49547  Washington      M  High School or Below   
...       ...         ...    ...                   ...   
4003      NaN         NaN    NaN                   NaN   
4004      NaN         NaN    NaN                   NaN   
4005      NaN         NaN    NaN                   NaN   
4006      NaN         NaN    NaN                   NaN   
4007      NaN         NaN    NaN                   NaN   

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0   
1                 697953.59%      0.0                  94.0   
2                1288743.17%  48767.0                 108.0   
3                 764586.18%      0.0                 106.0   
4                 536307.65%  36357.0                  68.0   
...                      ...      ...                   ...   
4003                     NaN      NaN                   NaN   
4004                     NaN      NaN                   NaN   
4005                     NaN      NaN                   NaN   
4006                     NaN      NaN                   NaN   
4007                     NaN      NaN                   NaN   

     Number of Open Complaints     Policy Type  Vehicle Class  \
0                       1/0/00   Personal Auto  Four-Door Car   
1                       1/0/00   Personal Auto  Four-Door Car   
2                       1/0/00   Personal Auto   Two-Door Car   
3                       1/0/00  Corporate Auto            SUV   
4                       1/0/00   Personal Auto  Four-Door Car   
...                        ...             ...            ...   
4003                       NaN             NaN            NaN   
4004                       NaN             NaN            NaN   
4005                       NaN             NaN            NaN   
4006                       NaN             NaN            NaN   
4007                       NaN             NaN            NaN   

      Total Claim Amount  
0               2.704934  
1            1131.464935  
2             566.472247  
3             529.881344  
4              17.269323  
...                  ...  
4003                 NaN  
4004                 NaN  
4005                 NaN  
4006                 NaN  
4007                 NaN  

[4008 rows x 11 columns]

In [273]:
file2.head()

Customer          ST GENDER Education Customer Lifetime Value  Income  \
0  GS98873     Arizona      F  Bachelor              323912.47%   16061   
1  CW49887  California      F    Master              462680.11%   79487   
2  MY31220  California      F   College              899704.02%   54230   
3  UH35128      Oregon      F   College             2580706.30%   71210   
4  WH52799     Arizona      F   College              380812.21%   94903   

   Monthly Premium Auto Number of Open Complaints  Total Claim Amount  \
0                    88                    1/0/00               633.6   
1                   114                    1/0/00               547.2   
2                   112                    1/0/00               537.6   
3                   214                    1/1/00              1027.2   
4                    94                    1/0/00               451.2   

      Policy Type  Vehicle Class  
0   Personal Auto  Four-Door Car  
1    Special Auto            SUV  
2   Personal Auto   Two-Door Car  
3   Personal Auto     Luxury Car  
4  Corporate Auto   Two-Door Car

In [274]:
file3.head()

Customer       State  Customer Lifetime Value             Education Gender  \
0  SA25987  Washington              3479.137523  High School or Below      M   
1  TB86706     Arizona              2502.637401                Master      M   
2  ZL73902      Nevada              3265.156348              Bachelor      F   
3  KX23516  California              4455.843406  High School or Below      F   
4  FN77294  California              7704.958480  High School or Below      M   

   Income  Monthly Premium Auto  Number of Open Complaints    Policy Type  \
0       0                   104                          0  Personal Auto   
1       0                    66                          0  Personal Auto   
2   25820                    82                          0  Personal Auto   
3       0                   121                          0  Personal Auto   
4   30366                   101                          2  Personal Auto   

   Total Claim Amount  Vehicle Class  
0          499.200000   Two-Door Car  
1            3.468912   Two-Door Car  
2          393.600000  Four-Door Car  
3          699.615192            SUV  
4          484.800000            SUV

In [275]:
#2) Show the DataFrame's shape.

file1.shape
file2.shape
file3.shape

(7070, 11)

In [276]:
#3) Standardize header names.

file1.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [277]:
file2.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Total Claim Amount', 'Policy Type', 'Vehicle Class'],
      dtype='object')

In [278]:
file3.columns

Index(['Customer', 'State', 'Customer Lifetime Value', 'Education', 'Gender',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Total Claim Amount', 'Vehicle Class'],
      dtype='object')

In [279]:
file1.columns == file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False])

In [280]:
file2 = file2.reindex(columns=['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints', 'Policy Type','Vehicle Class',
       'Total Claim Amount'])

In [281]:
file1.columns == file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [282]:
file2.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

In [283]:
display(file1.columns)
display(file3.columns)

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='object')

Index(['Customer', 'State', 'Customer Lifetime Value', 'Education', 'Gender',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Total Claim Amount', 'Vehicle Class'],
      dtype='object')

In [284]:
cols = []
for i in range(len(file1.columns)):
    cols.append(file1.columns[i].lower())
file1.columns = cols

In [285]:
file1.head()

customer          st gender             education customer lifetime value  \
0  RB50392  Washington    NaN                Master                     NaN   
1  QZ44356     Arizona      F              Bachelor              697953.59%   
2  AI49188      Nevada      F              Bachelor             1288743.17%   
3  WW63253  California      M              Bachelor              764586.18%   
4  GA49547  Washington      M  High School or Below              536307.65%   

    income  monthly premium auto number of open complaints     policy type  \
0      0.0                1000.0                    1/0/00   Personal Auto   
1      0.0                  94.0                    1/0/00   Personal Auto   
2  48767.0                 108.0                    1/0/00   Personal Auto   
3      0.0                 106.0                    1/0/00  Corporate Auto   
4  36357.0                  68.0                    1/0/00   Personal Auto   

   vehicle class  total claim amount  
0  Four-Door Car            2.704934  
1  Four-Door Car         1131.464935  
2   Two-Door Car          566.472247  
3            SUV          529.881344  
4  Four-Door Car           17.269323

In [286]:
file1.columns == file2.columns

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [287]:
cols = []
for i in range(len(file2.columns)):
    cols.append(file2.columns[i].lower())
file2.columns = cols

In [288]:
file1.columns == file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [289]:
cols = []
for i in range(len(file3.columns)):
    cols.append(file3.columns[i].lower())
file3.columns = cols

In [290]:
file3.head()

customer       state  customer lifetime value             education gender  \
0  SA25987  Washington              3479.137523  High School or Below      M   
1  TB86706     Arizona              2502.637401                Master      M   
2  ZL73902      Nevada              3265.156348              Bachelor      F   
3  KX23516  California              4455.843406  High School or Below      F   
4  FN77294  California              7704.958480  High School or Below      M   

   income  monthly premium auto  number of open complaints    policy type  \
0       0                   104                          0  Personal Auto   
1       0                    66                          0  Personal Auto   
2   25820                    82                          0  Personal Auto   
3       0                   121                          0  Personal Auto   
4   30366                   101                          2  Personal Auto   

   total claim amount  vehicle class  
0          499.200000   Two-Door Car  
1            3.468912   Two-Door Car  
2          393.600000  Four-Door Car  
3          699.615192            SUV  
4          484.800000            SUV

In [291]:
file1.columns==file3.columns

array([ True, False, False,  True, False,  True,  True,  True,  True,
       False, False])

In [292]:
display(file1.columns)
display(file3.columns)

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

Index(['customer', 'state', 'customer lifetime value', 'education', 'gender',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'total claim amount', 'vehicle class'],
      dtype='object')

In [293]:
file3 = file3.reindex(columns=['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'])

In [294]:
file3.head()

customer       state gender             education  customer lifetime value  \
0  SA25987  Washington      M  High School or Below              3479.137523   
1  TB86706     Arizona      M                Master              2502.637401   
2  ZL73902      Nevada      F              Bachelor              3265.156348   
3  KX23516  California      F  High School or Below              4455.843406   
4  FN77294  California      M  High School or Below              7704.958480   

   income  monthly premium auto  number of open complaints    policy type  \
0       0                   104                          0  Personal Auto   
1       0                    66                          0  Personal Auto   
2   25820                    82                          0  Personal Auto   
3       0                   121                          0  Personal Auto   
4   30366                   101                          2  Personal Auto   

   vehicle class  total claim amount  
0   Two-Door Car          499.200000  
1   Two-Door Car            3.468912  
2  Four-Door Car          393.600000  
3            SUV          699.615192  
4            SUV          484.800000

In [295]:
file1.columns==file3.columns

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [296]:
display(file1.columns)
display(file2.columns)
display(file3.columns)

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

Index(['customer', 'st', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

In [297]:
file1 = file1.rename(columns={'st':'state'})
file2 = file1.rename(columns={'st':'state'})

display(file1.columns)
display(file2.columns)
display(file3.columns)

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

Index(['customer', 'state', 'gender', 'education', 'customer lifetime value',
       'income', 'monthly premium auto', 'number of open complaints',
       'policy type', 'vehicle class', 'total claim amount'],
      dtype='object')

In [298]:
file1.columns==file2.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [299]:
file1.columns==file3.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [300]:
#Rearrange the columns in the dataframe as needed 

In [301]:
#Concatenate the three dataframes

data = pd.concat([file1,file2,file3],axis=0)
data.shape

(15086, 11)

In [302]:
display(file1.shape)
display(file2.shape)
display(file3.shape)

file1.shape[0]

(4008, 11)

(4008, 11)

(7070, 11)

4008

In [303]:
file1.shape[0]+file2.shape[0]+file3.shape[0] == data.shape[0]

True

In [304]:
data.head()

customer       state gender             education customer lifetime value  \
0  RB50392  Washington    NaN                Master                     NaN   
1  QZ44356     Arizona      F              Bachelor              697953.59%   
2  AI49188      Nevada      F              Bachelor             1288743.17%   
3  WW63253  California      M              Bachelor              764586.18%   
4  GA49547  Washington      M  High School or Below              536307.65%   

    income  monthly premium auto number of open complaints     policy type  \
0      0.0                1000.0                    1/0/00   Personal Auto   
1      0.0                  94.0                    1/0/00   Personal Auto   
2  48767.0                 108.0                    1/0/00   Personal Auto   
3      0.0                 106.0                    1/0/00  Corporate Auto   
4  36357.0                  68.0                    1/0/00   Personal Auto   

   vehicle class  total claim amount  
0  Four-Door Car            2.704934  
1  Four-Door Car         1131.464935  
2   Two-Door Car          566.472247  
3            SUV          529.881344  
4  Four-Door Car           17.269323

In [305]:
data = data.reset_index(drop=True)

In [306]:
data

customer       state gender             education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
15081  LA72316  California      M              Bachelor   
15082  PK87824  California      F               College   
15083  TD14365  California      M              Bachelor   
15084  UP19263  California      M               College   
15085  Y167826  California      M               College   

      customer lifetime value   income  monthly premium auto  \
0                         NaN      0.0                1000.0   
1                  697953.59%      0.0                  94.0   
2                 1288743.17%  48767.0                 108.0   
3                  764586.18%      0.0                 106.0   
4                  536307.65%  36357.0                  68.0   
...                       ...      ...                   ...   
15081             23405.98798  71941.0                  73.0   
15082             3096.511217  21604.0                  79.0   
15083             8163.890428      0.0                  85.0   
15084             7524.442436  21941.0                  96.0   
15085             2611.836866      0.0                  77.0   

      number of open complaints     policy type  vehicle class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
15081                         0   Personal Auto  Four-Door Car   
15082                         0  Corporate Auto  Four-Door Car   
15083                         3  Corporate Auto  Four-Door Car   
15084                         0   Personal Auto  Four-Door Car   
15085                         0  Corporate Auto   Two-Door Car   

       total claim amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
15081          198.234764  
15082          379.200000  
15083          790.784983  
15084          691.200000  
15085          369.600000  

[15086 rows x 11 columns]

In [307]:
#Which columns are numerical? Which columns are categorical?
print(data.dtypes)

customer                      object
state                         object
gender                        object
education                     object
customer lifetime value       object
income                       float64
monthly premium auto         float64
number of open complaints     object
policy type                   object
vehicle class                 object
total claim amount           float64
dtype: object


In [308]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15086 entries, 0 to 15085
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   customer                   9212 non-null   object 
 1   state                      9212 non-null   object 
 2   gender                     8978 non-null   object 
 3   education                  9212 non-null   object 
 4   customer lifetime value    9206 non-null   object 
 5   income                     9212 non-null   float64
 6   monthly premium auto       9212 non-null   float64
 7   number of open complaints  9212 non-null   object 
 8   policy type                9212 non-null   object 
 9   vehicle class              9212 non-null   object 
 10  total claim amount         9212 non-null   float64
dtypes: float64(3), object(8)
memory usage: 1.3+ MB


In [309]:
#Understand the meaning of all columns

In [310]:
#Delete the column education and the number of open complaints from the dataframe.

# data = data.drop(['education','number of open complaints'], axis=1)

data

customer       state gender             education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
15081  LA72316  California      M              Bachelor   
15082  PK87824  California      F               College   
15083  TD14365  California      M              Bachelor   
15084  UP19263  California      M               College   
15085  Y167826  California      M               College   

      customer lifetime value   income  monthly premium auto  \
0                         NaN      0.0                1000.0   
1                  697953.59%      0.0                  94.0   
2                 1288743.17%  48767.0                 108.0   
3                  764586.18%      0.0                 106.0   
4                  536307.65%  36357.0                  68.0   
...                       ...      ...                   ...   
15081             23405.98798  71941.0                  73.0   
15082             3096.511217  21604.0                  79.0   
15083             8163.890428      0.0                  85.0   
15084             7524.442436  21941.0                  96.0   
15085             2611.836866      0.0                  77.0   

      number of open complaints     policy type  vehicle class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
15081                         0   Personal Auto  Four-Door Car   
15082                         0  Corporate Auto  Four-Door Car   
15083                         3  Corporate Auto  Four-Door Car   
15084                         0   Personal Auto  Four-Door Car   
15085                         0  Corporate Auto   Two-Door Car   

       total claim amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
15081          198.234764  
15082          379.200000  
15083          790.784983  
15084          691.200000  
15085          369.600000  

[15086 rows x 11 columns]

In [311]:
#Correct the values in the column customer lifetime value. They are given as a percent, so multiply (divide) them by 100 and change dtype to numerical type.

In [312]:
data['customer lifetime value'] = pd.to_numeric(data['customer lifetime value'], errors='coerce')

In [313]:
data['customer lifetime value']= data['customer lifetime value']/100

In [314]:
data.loc[:,'customer lifetime value']

0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
            ...    
15081    234.059880
15082     30.965112
15083     81.638904
15084     75.244424
15085     26.118369
Name: customer lifetime value, Length: 15086, dtype: float64

In [315]:
#Check for duplicate rows in the data and remove if any.

data = data.drop_duplicates()

In [316]:
data

customer       state gender             education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
2      AI49188      Nevada      F              Bachelor   
3      WW63253  California      M              Bachelor   
4      GA49547  Washington      M  High School or Below   
...        ...         ...    ...                   ...   
15081  LA72316  California      M              Bachelor   
15082  PK87824  California      F               College   
15083  TD14365  California      M              Bachelor   
15084  UP19263  California      M               College   
15085  Y167826  California      M               College   

       customer lifetime value   income  monthly premium auto  \
0                          NaN      0.0                1000.0   
1                          NaN      0.0                  94.0   
2                          NaN  48767.0                 108.0   
3                          NaN      0.0                 106.0   
4                          NaN  36357.0                  68.0   
...                        ...      ...                   ...   
15081               234.059880  71941.0                  73.0   
15082                30.965112  21604.0                  79.0   
15083                81.638904      0.0                  85.0   
15084                75.244424  21941.0                  96.0   
15085                26.118369      0.0                  77.0   

      number of open complaints     policy type  vehicle class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
2                        1/0/00   Personal Auto   Two-Door Car   
3                        1/0/00  Corporate Auto            SUV   
4                        1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
15081                         0   Personal Auto  Four-Door Car   
15082                         0  Corporate Auto  Four-Door Car   
15083                         3  Corporate Auto  Four-Door Car   
15084                         0   Personal Auto  Four-Door Car   
15085                         0  Corporate Auto   Two-Door Car   

       total claim amount  
0                2.704934  
1             1131.464935  
2              566.472247  
3              529.881344  
4               17.269323  
...                   ...  
15081          198.234764  
15082          379.200000  
15083          790.784983  
15084          691.200000  
15085          369.600000  

[8142 rows x 11 columns]

In [333]:
# Filter out the data for customers who have an income of 0 or less.

data[(data['income']==0) | (data['income']<0)]


customer       state gender             education  \
0      RB50392  Washington    NaN                Master   
1      QZ44356     Arizona      F              Bachelor   
3      WW63253  California      M              Bachelor   
7      CF85061     Arizona      M                Master   
10     SX51350  California      M               College   
...        ...         ...    ...                   ...   
15075  WZ45103  California      F              Bachelor   
15077  RX91025  California      M  High School or Below   
15078  AC13887  California      M              Bachelor   
15083  TD14365  California      M              Bachelor   
15085  Y167826  California      M               College   

       customer lifetime value  income  monthly premium auto  \
0                          NaN     0.0                1000.0   
1                          NaN     0.0                  94.0   
3                          NaN     0.0                 106.0   
7                          NaN     0.0                 101.0   
10                         NaN     0.0                  67.0   
...                        ...     ...                   ...   
15075                56.780502     0.0                  76.0   
15077               198.722620     0.0                 185.0   
15078                46.289953     0.0                  67.0   
15083                81.638904     0.0                  85.0   
15085                26.118369     0.0                  77.0   

      number of open complaints     policy type  vehicle class  \
0                        1/0/00   Personal Auto  Four-Door Car   
1                        1/0/00   Personal Auto  Four-Door Car   
3                        1/0/00  Corporate Auto            SUV   
7                        1/0/00  Corporate Auto  Four-Door Car   
10                       1/0/00   Personal Auto  Four-Door Car   
...                         ...             ...            ...   
15075                         0   Personal Auto  Four-Door Car   
15077                         0   Personal Auto            SUV   
15078                         0  Corporate Auto   Two-Door Car   
15083                         3  Corporate Auto  Four-Door Car   
15085                         0  Corporate Auto   Two-Door Car   

       total claim amount  
0                2.704934  
1             1131.464935  
3              529.881344  
7              363.029680  
10             482.400000  
...                   ...  
15075          364.800000  
15077         1950.725547  
15078          482.400000  
15083          790.784983  
15085          369.600000  

[2073 rows x 11 columns]